# -*- coding: utf-8 -*-
"""recommend_song.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uwMLsANVi8isQjtztq4GA-TllyoUhnVe

# Step 1: Create a Spotify Developer Account & App
"""

"""# Step 2: Install Spotipy in Colab"""

# !pip install spotipy

"""# Step 3: Authenticate with Spotify API"""

import spotipy
from spotipy.oauth2 import SpotifyClientCredentials

# Replace with your actual Client ID and Secret
CLIENT_ID = ''
CLIENT_SECRET = ''

auth_manager = SpotifyClientCredentials(client_id=CLIENT_ID, client_secret=CLIENT_SECRET)
sp = spotipy.Spotify(auth_manager=auth_manager)

"""# Step 4: Emotion to Genre/Keyword Mapping"""

emotion_to_genre = {
    "happy": "happy pop",
    "sad": "sad acoustic",
    "angry": "metal",
    "surprise": "party",
    "neutral": "chill",
    "fear": "ambient",
    "disgust": "dark"
}

"""# Step 5: Define recommend_song() Function"""

def recommend_song(emotion, limit=3):
    genre = emotion_to_genre.get(emotion.lower(), "pop")  # default genre
    results = sp.search(q=genre, limit=limit, type='track')

    recommendations = []
    for idx, track in enumerate(results['tracks']['items']):
        name = track['name']
        artist = track['artists'][0]['name']
        url = track['external_urls']['spotify']
        recommendations.append(f"{idx+1}. {name} by {artist} - [Listen]({url})")

    return recommendations
